name: Build and push new lambda images to AWS S3

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: us-east-1
  S3_BUCKET: finapp-lambdas

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get commit SHA
        id: commit_sha
        run: echo "::set-output name=SHA::$(echo $GITHUB_SHA | cut -c1-7)"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@0e613a0980cbf65ed5b322eb7a1e075d28913a83
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Check if S3 bucket exists
        id: check_bucket
        run: |
          if aws s3 ls s3://${{ env.S3_BUCKET }} >/dev/null 2>&1; then
          echo "::set-output name=exists::true"
          else
          echo "::set-output name=exists::false"
          fi
          
      - name: Create S3 bucket if it does not exist
        if: steps.check_bucket.outputs.exists == 'false'
        run: |
          aws s3 mb s3://${{ env.S3_BUCKET }} --region ${{ env.AWS_REGION }}

      - name: Create lambda artifacts
        run: |
          echo "Creating artifact folder"
          mkdir artifacts/"$SHA"
          lambda_layers=$(find "." -maxdepth 1 -type f -name "*.py" | sed 's/\.py$//')
          for loop in $lambda_layers
          do
          zip artifacts/"$SHA"/"$loop".zip $loop.py
          done

      - name: Upload lambda artifacts to S3
        run: |
          aws s3 sync artifacts/"$SHA" s3://$S3_BUCKET/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ env.AWS_REGION }}
          S3_BUCKET: ${{ env.S3_BUCKET }}
          SHA: ${{ steps.commit_sha.outputs.SHA }}
